# See: https://hub.zhox.com/posts/introducing-haskell-dev/

environment:
  global:
    CABOPTS: --store-dir=C:\\SR --http-transport=plain-http
    GHCVER: 8.8.2

install:
  - choco source add -n mistuke -s  https://www.myget.org/F/mistuke/api/v2
  - choco install -y cabal --version 3.0.0.0
  - choco install -y ghc --version %GHCVER%
  - refreshenv

before_build:
  - cabal --version
  - ghc --version
  - cabal %CABOPTS% v2-update

clone_folder: "c:\\WORK"

cache:
  - C:\sr

build_script:
  - cabal %CABOPTS% v2-configure --enable-test --enable-coverage
  - cabal %CABOPTS% v2-build
  - cabal %CABOPTS% v2-test
  - cabal %CABOPTS% v2-exec -- hpc-codecov --version > v.txt
  - set /p VERSION=<v.txt
  - set G=C:\WORK\dist-newstyle\build\x86_64-windows\ghc-%GHCVER%
  - set PROJ=hpc-codecov-%VERSION%
  - set VANILLA=%G%\%PROJ%\hpc\vanilla
  - set MIX=%VANILLA%\mix\%PROJ%
  - set TIX=%VANILLA%\tix\%PROJ%\%PROJ%.tix
  - cabal %CABOPTS% v2-exec -- hpc-codecov --mix=%MIX% -o reports %TIX%
  - curl -s https://codecov.io/bash > codecov.sh
  - bash codecov.sh -f reports
