# See: https://hub.zhox.com/posts/introducing-haskell-dev/
# for settings with cabal-install.

# environment:
#   global:
#     CABOPTS: --store-dir=C:\\SR --http-transport=plain-http
#     GHCVER: 9.4.2
#     CABALVER: 3.8.1.0

install:
  - choco install -y haskell-stack
  - refreshenv

before_build:
  - stack setup

clone_folder: "c:\\WORK"

cache:
  - C:\sr

build_script:
  - stack build --test --coverage
  - stack exec -- hpc-codecov --verbose stack:test-main -o codecov.json
  - curl -Os https://uploader.codecov.io/latest/windows/codecov.exe
  - .\codecov.exe
