comment:
  layout: "header, reach, diff, flags, files"
  hide_project_coverage: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        base: auto
        informational: true
    patch:
      default:
        target: auto
        threshold: 10%
        base: auto
        informational: true
