name: ci

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

env:
  cache-version: v2

defaults:
  run:
    shell: bash

jobs:
  stack:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on:
      - ${{ matrix.os }}

    steps:
    - name: Checkout project repository
      uses: actions/checkout@v3

    - name: Show stack version
      run: stack --version

    - name: Get stack root
      id: stack-root
      env:
        os: ${{ runner.os }}
      run: |
        echo os=$os
        case $os in
          "Linux")
             echo "path=$HOME/.stack" >> $GITHUB_OUTPUT
             ;;
          "macOS")
             echo "path=$HOME/.stack" >> $GITHUB_OUTPUT
             ;;
          *)
             echo "path=C:/Users/runneradmin/AppData/Roaming/stack" >> $GITHUB_OUTPUT
             ;;
        esac

    - name: Cache stack root
      if: runner.os != 'macOS'
      id: stack-global
      uses: actions/cache@v2
      with:
        path: ${{ steps.stack-root.outputs.path }}
        key: ${{ runner.os }}-stack-global-${{ hashFiles('**.yaml') }}-${{ env.cache-version }}

    - name: Cache windows optional data for stack
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\AppData\Local\Programs\stack
        key: ${{ runner.os }}-stack-program-${{ hashFiles('**.yaml') }}-${{ env.cache-version }}

    - name: Set stack to use system ghc
      run: stack config set system-ghc --global true

    - name: Install dependency packages
      run: stack build --fast --test --coverage --only-dependencies

    - name: Build packages
      run: stack build --fast --test --coverage --no-run-tests

    - name: Run tests
      run: stack build --fast --test --coverage

    - name: Generate coverage report
      run: |
        STACK="stack"
        HPCROOT=$($STACK path --local-hpc-root)
        TIX=$(find $HPCROOT -name 'test-main.tix')
        MIX=$($STACK path --dist-dir)/hpc
        $STACK exec -- hpc-codecov --verbose --mix=$MIX -o codecov.json $TIX

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        name: gh-stack-${{ matrix.os }}

  cabal-install:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on:
      - ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show versions
        run: |
          ghc --version
          cabal --version

      - name: Configure
        run: cabal configure --enable-executable-stripping

      - name: Set .exe extension on windows
        if: matrix.os == 'windows-latest'
        id: extension
        run: echo "exe=.exe" >> $GITHUB_OUTPUT

      - name: Set executable
        id: bin
        run: echo "path=bin/hpc-codecov-${{ runner.os }}${{ steps.extension.outputs.exe }}" >> $GITHUB_OUTPUT

      - name: Create bin directory
        run: mkdir ./bin/

      - name: Install to current directory
        run: cabal install --install-method=copy --installdir=./bin

      - name: Rename the executable
        run: mv -v bin/hpc-codecov${{ steps.extension.outputs.exe}} ${{ steps.bin.outputs.path }}

      - name: Show executable
        run: ls -lh ${{ steps.bin.outputs.path }}

      - name: Strip executable
        if: matrix.os != 'macos-latest'
        run: strip -s ${{ steps.bin.outputs.path }}

      - name: Compress executable
        uses: svenstaro/upx-action@v2
        with:
          file: ${{ steps.bin.outputs.path }}
          args: -9
          strip: false

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bins
          path: ${{ steps.bin.outputs.path }}

  via-action:
    name: Run hpc-codecov-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup cabal
        run: cabal update

      - name: Build and test
        run: cabal test --enable-coverage

      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@v2
        with:
          build-tool: cabal
          test-suite: test-main
          excludes: Main,Test.Main,Paths_hpc_codecov

      - name: Send coverage report
        uses: codecov/codecov-action@v3
        with:
          name: hpc-codecov-action

  release:
    name: Release on new tag
    runs-on: ubuntu-latest
    needs:
      - stack
      - cabal-install

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: bins
          path: bin

      - name: Show contents of the bin directory
        run: ls -lh bin

      - name: Make release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        id: rel
        with:
          draft: true
          prerelease: true
          body: ''
          files: |
            bin/hpc-codecov-Linux
            bin/hpc-codecov-Windows.exe
            bin/hpc-codecov-macOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show released URL
        if: startsWith(github.ref, 'refs/tags')
        run: echo ${{ steps.rel.outputs.url }}
