name: ci

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: bash

jobs:
  pre_job:
    uses: ./.github/workflows/pre_job.yml

  stack:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.run_it == 'true' }}
    uses: ./.github/workflows/stack.yml
    secrets: inherit
    with:
      cache: v3

  cabal-install:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.run_it == 'true' }}
    uses: ./.github/workflows/cabal-install.yml
    with:
      cache: v3

  # via-action:
  #   needs: pre_job
  #   if: ${{ needs.pre_job.outputs.run_it == 'true' }}
  #   uses: ./.github/workflows/via-action.yml
  #   secrets: inherit

  static-executable-for-linux:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.run_it == 'true' }}
    uses: ./.github/workflows/static-executable.yml

  container-image:
    needs: static-executable-for-linux
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    uses: ./.github/workflows/container-image.yml
    secrets: inherit
      
  release:
    needs:
      - stack
      - cabal-install
      - static-executable-for-linux
    if: startsWith(github.ref, 'refs/tags')
    uses: ./.github/workflows/release.yml
    secrets: inherit
