name: Static executable for Linux

on:
  workflow_call:

jobs:
  static-executable-for-linux:
    name: Build static executable for Linux
    runs-on: ubuntu-latest
    env:
      exe: hpc-codecov-Linux-X64-static
    container:
      image: fossa/haskell-static-alpine:ghc-9.8.2
    steps:
      - name: Show versions
        run: |
          which ghc && ghc --version
          which cabal && cabal --version

      - name: Checkout
        uses: actions/checkout@v5

      - name: Update cabal package index
        run: cabal update

      - name: Run cabal configure
        run: cabal configure -O2 --enable-executable-static

      - name: Show cabal.project.local
        run: cat cabal.project.local

      - name: Run cabal build
        run: cabal build

      - name: Copy the executable
        run: mkdir ./bin && cp -v $(cabal list-bin hpc-codecov) ./bin/${{ env.exe }}

      - name: Strip the executable
        run: strip -s ./bin/${{ env.exe }}

      - name: Run readelf
        run: readelf -d ./bin/${{ env.exe }}

      - name: Compress executable
        uses: svenstaro/upx-action@v2
        with:
          files: ./bin/${{ env.exe }}
          args: -9
          strip: false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.exe }}
          path: bin/${{ env.exe }}
